theme: jekyll-theme-minimal
title: Abdur Rahman Onik
description: Executive-IT, Opsonin Pharma Limited.  
**[Google Scholar](https://scholar.google.com/citations?user=uLJZeTQAAAAJ&hl=en) ||  [Linkdin](https://www.linkedin.com/in/rahmanonik/)**
